export declare const api: {
    login: (username: string, password: string) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    me: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    overview: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    loginTrend: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    dashboardCharts: (days?: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listAdmins: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    createAdmin: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateAdmin: (id: number, payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    deleteAdmin: (id: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listUsers: (params: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    createUser: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateUser: (id: number, payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    deleteUser: (id: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listAgents: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    createAgent: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateAgent: (id: number, payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    deleteAgent: (id: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    optimizeAgent: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    playgroundAgent: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listQuestions: (params: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listAnswers: (params: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listComments: (params: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateQuestion: (id: number, payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateAnswer: (id: number, payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateComment: (id: number, payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    deleteQuestion: (id: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    deleteAnswer: (id: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    deleteComment: (id: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    debateStart: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    debateStop: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    debateStatus: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    debateHistory: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    createCrawlerJob: (source: "zhihu" | "weibo") => Promise<import("axios").AxiosResponse<any, any, {}>>;
    listCrawlerJobs: (params?: {
        source?: "zhihu" | "weibo";
        limit?: number;
    }) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getCrawlerJob: (jobId: string) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getCrawlerJobLogs: (jobId: string, tail?: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    runZhihuCrawler: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    runWeiboCrawler: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getRuntimeConfig: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateRuntimeConfig: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getQaPolicy: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateQaPolicy: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getDebatePolicy: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateDebatePolicy: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getSchedulerPolicy: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateSchedulerPolicy: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getRealtimePolicy: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    updateRealtimePolicy: (payload: any) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getRuntimeCapacity: () => Promise<import("axios").AxiosResponse<any, any, {}>>;
    getLlmAlerts: (limit?: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    ackLlmAlerts: (ids: string[]) => Promise<import("axios").AxiosResponse<any, any, {}>>;
    streamUrl: (channel: "hotspots" | "questions" | "debates" | "agents" | "online") => string;
    auditLogs: (limit?: number) => Promise<import("axios").AxiosResponse<any, any, {}>>;
};
