import http from "./http";
export const api = {
    login: (username, password) => http.post("/admin/auth/login", { username, password }),
    me: () => http.get("/admin/auth/me"),
    overview: () => http.get("/admin/dashboard/overview"),
    loginTrend: () => http.get("/admin/dashboard/login-trend"),
    dashboardCharts: (days = 7) => http.get("/admin/dashboard/charts", { params: { days } }),
    listAdmins: () => http.get("/admin/admin-users"),
    createAdmin: (payload) => http.post("/admin/admin-users", payload),
    updateAdmin: (id, payload) => http.patch(`/admin/admin-users/${id}`, payload),
    deleteAdmin: (id) => http.delete(`/admin/admin-users/${id}`),
    listUsers: (params) => http.get("/admin/users", { params }),
    createUser: (payload) => http.post("/admin/users", payload),
    updateUser: (id, payload) => http.patch(`/admin/users/${id}`, payload),
    deleteUser: (id) => http.delete(`/admin/users/${id}`),
    listAgents: () => http.get("/admin/agents"),
    createAgent: (payload) => http.post("/admin/agents", payload),
    updateAgent: (id, payload) => http.patch(`/admin/agents/${id}`, payload),
    deleteAgent: (id) => http.delete(`/admin/agents/${id}`),
    optimizeAgent: (payload) => http.post("/admin/agents/optimize", payload),
    playgroundAgent: (payload) => http.post("/admin/agents/playground", payload),
    listQuestions: (params) => http.get("/admin/content/questions", { params }),
    listAnswers: (params) => http.get("/admin/content/answers", { params }),
    listComments: (params) => http.get("/admin/content/comments", { params }),
    updateQuestion: (id, payload) => http.patch(`/admin/content/questions/${id}`, payload),
    updateAnswer: (id, payload) => http.patch(`/admin/content/answers/${id}`, payload),
    updateComment: (id, payload) => http.patch(`/admin/content/comments/${id}`, payload),
    deleteQuestion: (id) => http.delete(`/admin/content/questions/${id}`),
    deleteAnswer: (id) => http.delete(`/admin/content/answers/${id}`),
    deleteComment: (id) => http.delete(`/admin/content/comments/${id}`),
    purgeContentByDate: (payload) => http.post("/admin/content/purge-by-date", payload),
    debateStart: (payload) => http.post("/admin/ops/debate/start", payload),
    debateStop: () => http.post("/admin/ops/debate/stop"),
    debateStatus: () => http.get("/admin/ops/debate/status"),
    debateHistory: () => http.get("/admin/ops/debate/history"),
    createCrawlerJob: (source) => http.post(`/admin/ops/crawler/${source}/jobs`),
    listCrawlerJobs: (params) => http.get("/admin/ops/crawler/jobs", { params }),
    getCrawlerJob: (jobId) => http.get(`/admin/ops/crawler/jobs/${jobId}`),
    getCrawlerJobLogs: (jobId, tail = 200) => http.get(`/admin/ops/crawler/jobs/${jobId}/logs`, { params: { tail } }),
    runZhihuCrawler: () => http.post("/admin/ops/crawler/zhihu/jobs"),
    runWeiboCrawler: () => http.post("/admin/ops/crawler/weibo/jobs"),
    getRuntimeConfig: () => http.get("/admin/ops/runtime-config"),
    updateRuntimeConfig: (payload) => http.put("/admin/ops/runtime-config", payload),
    getQaPolicy: () => http.get("/admin/ops/runtime/qa-policy"),
    updateQaPolicy: (payload) => http.put("/admin/ops/runtime/qa-policy", payload),
    getDebatePolicy: () => http.get("/admin/ops/runtime/debate-policy"),
    updateDebatePolicy: (payload) => http.put("/admin/ops/runtime/debate-policy", payload),
    getSchedulerPolicy: () => http.get("/admin/ops/runtime/scheduler-policy"),
    updateSchedulerPolicy: (payload) => http.put("/admin/ops/runtime/scheduler-policy", payload),
    getRealtimePolicy: () => http.get("/admin/ops/runtime/realtime-policy"),
    updateRealtimePolicy: (payload) => http.put("/admin/ops/runtime/realtime-policy", payload),
    getRuntimeCapacity: () => http.get("/admin/ops/runtime/capacity"),
    getLlmAlerts: (limit = 100) => http.get("/admin/ops/runtime/llm-alerts", { params: { limit } }),
    ackLlmAlerts: (ids) => http.post("/admin/ops/runtime/llm-alerts/ack", { ids }),
    streamUrl: (channel) => `/api/admin/stream/${channel}`,
    auditLogs: (limit = 100) => http.get("/admin/ops/audit/logs", { params: { limit } }),
};
