"""
LLM client for question/answer generation.
"""

import logging
import re
from typing import Dict, List, Optional

from langchain_core.prompts import ChatPromptTemplate

from app import prompts
from app.core.llm_runtime import run_with_llm_failover
from app.schemas.models import AgentInfo, AnswerOutput, QuestionOutput

logger = logging.getLogger("agent_service")


class LLMClient:
    def __init__(self):
        pass

    def _clean_markdown_formatting(self, text: str) -> str:
        if not text:
            return text
        text = re.sub(r"```[\w]*\n?", "", text)
        text = re.sub(r"```", "", text)
        text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
        text = re.sub(r"\*([^*]+)\*", r"\1", text)
        text = re.sub(r"^(#{1,6})\s+", "", text, flags=re.MULTILINE)
        text = re.sub(r"^[\s]*[-*]\s+", "", text, flags=re.MULTILINE)
        text = re.sub(r"^[\s]*\d+\.\s+", "", text, flags=re.MULTILINE)
        lines = text.split("\n")
        cleaned_lines = [line.lstrip() for line in lines]
        text = "\n".join(cleaned_lines)
        text = re.sub(r"\n{3,}", "\n\n", text)
        return text.strip()

    def _get_system_prompt(self, agent: AgentInfo) -> str:
        if agent.system_prompt:
            return agent.system_prompt

        local_prompt = prompts.SYSTEM_AGENT_PROMPTS.get(agent.username)
        if local_prompt:
            return local_prompt

        return (
            f"你是一个名叫“{agent.username}”的知乎用户，风格是{agent.persona}。"
            "请以真人口吻发言。"
        )

    def _format_search_results(self, search_results: Optional[List[Dict]]) -> str:
        if not search_results:
            return ""

        items = []
        for i, result in enumerate(search_results[:5], 1):
            items.append(
                f"[{i}] {result.get('title', '')}\n{result.get('content', '')[:500]}...\n来源: {result.get('url', '')}"
            )

        return "\n## 参考资料\n" + "\n\n".join(items)

    async def generate_question(
        self,
        agent: AgentInfo,
        category: str,
        topic: str,
        search_results: Optional[List[Dict]] = None,
        recent_questions: Optional[List[str]] = None,
        recent_topics: Optional[List[str]] = None,
    ) -> QuestionOutput:
        if not category or not topic:
            raise ValueError("category and topic cannot be empty")

        system_prompt = self._get_system_prompt(agent)
        expressiveness_instruction = prompts.QUESTION_EXPRESSIVENESS_INSTRUCTIONS.get(
            agent.expressiveness,
            prompts.QUESTION_EXPRESSIVENESS_INSTRUCTIONS["balanced"],
        )
        search_results_section = self._format_search_results(search_results)

        memory_section = ""
        if recent_questions or recent_topics:
            recent_questions_text = "\n".join(
                f"- {item}" for item in (recent_questions or [])[:10]
            )
            recent_topics_text = "\n".join(
                f"- {item}" for item in (recent_topics or [])[:10]
            )
            memory_section = prompts.QUESTION_MEMORY_SECTION.format(
                recent_questions_text=recent_questions_text or "- （暂无）",
                recent_topics_text=recent_topics_text or "- （暂无）",
            )

        payload = {
            "category": category,
            "topic": topic,
            "search_results_section": search_results_section,
            "memory_section": memory_section,
            "expressiveness_instruction": expressiveness_instruction,
        }

        try:
            async def _invoke(llm):
                chain = ChatPromptTemplate.from_messages(
                    [("system", system_prompt), ("human", prompts.QUESTION_USER_PROMPT)]
                ) | llm.with_structured_output(QuestionOutput, include_raw=False)
                return await chain.ainvoke(payload)

            result = await run_with_llm_failover(
                scene="qa.generate_question",
                runner=_invoke,
                max_tokens=2000,
            )
            result.content = self._clean_markdown_formatting(result.content)
            logger.info("[question] generated by %s: %s", agent.username, result.title)
            return result
        except Exception as e:
            logger.error("LLM generate_question failed: %s", e, exc_info=True)
            return QuestionOutput(
                title=f"关于{topic}的思考",
                content=f"在{category}领域，{topic}引发了广泛关注。",
                reasoning="LLM 调用失败，使用默认输出。",
                references=[],
            )

    async def generate_answer(
        self,
        agent: AgentInfo,
        question: Dict,
        search_results: Optional[List[Dict]] = None,
        existing_answers: Optional[List[str]] = None,
    ) -> AnswerOutput:
        if not question or not question.get("title"):
            raise ValueError("question must include title")

        system_prompt = self._get_system_prompt(agent)
        expressiveness_instruction = prompts.ANSWER_EXPRESSIVENESS_INSTRUCTIONS.get(
            agent.expressiveness,
            prompts.ANSWER_EXPRESSIVENESS_INSTRUCTIONS["balanced"],
        )
        search_results_section = self._format_search_results(search_results)

        existing_answers_section = ""
        if existing_answers:
            existing_answers_text = "\n".join(existing_answers)
            existing_answers_section = prompts.EXISTING_ANSWERS_SECTION.format(
                existing_answers_text=existing_answers_text
            )

        payload = {
            "question_title": question.get("title", ""),
            "question_content": question.get("content", "")[:300],
            "search_results_section": search_results_section,
            "expressiveness_instruction": expressiveness_instruction,
            "existing_answers_section": existing_answers_section,
        }

        try:
            async def _invoke(llm):
                chain = ChatPromptTemplate.from_messages(
                    [("system", system_prompt), ("human", prompts.ANSWER_USER_PROMPT)]
                ) | llm.with_structured_output(AnswerOutput, include_raw=False)
                return await chain.ainvoke(payload)

            result = await run_with_llm_failover(
                scene="qa.generate_answer",
                runner=_invoke,
                max_tokens=2000,
            )
            result.content = self._clean_markdown_formatting(result.content)
            logger.info("[answer] generated by %s", agent.username)
            return result
        except Exception as e:
            logger.error("LLM generate_answer failed: %s", e, exc_info=True)
            return AnswerOutput(
                content=f"作为一个{agent.persona}，我认为这个问题值得深入探讨。",
                viewpoint=f"{agent.persona}的视角分析（LLM 调用失败）",
                evidence=[],
                references=[],
            )

    async def generate(
        self,
        prompt: str,
        system_prompt: str = "",
        max_tokens: int = 2000,
        temperature: Optional[float] = None,
    ) -> str:
        messages = []
        if system_prompt:
            messages.append(("system", system_prompt))
        messages.append(("human", prompt))

        try:
            async def _invoke(llm):
                chain = ChatPromptTemplate.from_messages(messages) | llm
                result = await chain.ainvoke({})
                return str(result.content)

            return await run_with_llm_failover(
                scene="qa.generic_generate",
                runner=_invoke,
                max_tokens=max_tokens,
                temperature_override=temperature,
            )
        except Exception as e:
            logger.error("LLM generate failed: %s", e, exc_info=True)
            raise


llm_client = LLMClient()
