// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/answer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为问题创建一个新回答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回答管理"
                ],
                "summary": "创建回答",
                "parameters": [
                    {
                        "description": "回答参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"创建成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"问题不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/answer/feed": {
            "get": {
                "description": "获取回答列表（包含问题信息），使用游标分页，用于首页推荐/最新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回答管理"
                ],
                "summary": "获取回答Feed流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/answer/list": {
            "get": {
                "description": "获取指定问题的回答列表，使用游标分页，包含点赞/点踩/评论统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回答管理"
                ],
                "summary": "获取回答列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "问题ID",
                        "name": "question_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"缺少问题ID\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/answer/{id}": {
            "get": {
                "description": "根据ID获取回答详细信息，包含点赞/点踩/评论统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回答管理"
                ],
                "summary": "获取回答详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "回答ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"回答不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新回答内容（仅作者本人可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回答管理"
                ],
                "summary": "更新回答",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "回答ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"更新成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"回答不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除回答（仅作者本人可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回答管理"
                ],
                "summary": "删除回答",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "回答ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"删除成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"回答不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/collection": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新的收藏夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏管理"
                ],
                "summary": "创建收藏夹",
                "parameters": [
                    {
                        "description": "收藏夹名称",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"创建成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/collection/item": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将答案添加到指定收藏夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏管理"
                ],
                "summary": "添加答案到收藏夹",
                "parameters": [
                    {
                        "description": "收藏参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.AddToCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"收藏成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"收藏夹或答案不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "409": {
                        "description": "{\\\"code\\\": 409, \\\"message\\\": \\\"已经收藏过了\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从指定收藏夹中移除答案",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏管理"
                ],
                "summary": "从收藏夹移除答案",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "收藏夹ID",
                        "name": "collection_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "答案ID",
                        "name": "answer_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"移除成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"收藏夹不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/collection/items": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定收藏夹中的所有答案，使用游标分页，包含统计信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏管理"
                ],
                "summary": "获取收藏夹中的答案列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "收藏夹ID",
                        "name": "collection_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"收藏夹不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/collection/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有收藏夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏管理"
                ],
                "summary": "获取收藏夹列表",
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": [...]}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/collection/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定收藏夹（仅拥有者可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏管理"
                ],
                "summary": "删除收藏夹",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "收藏夹ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"删除成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"收藏夹不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/comment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为回答创建评论，支持根评论和回复评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "创建评论",
                "parameters": [
                    {
                        "description": "评论参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"创建成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"回答不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/comment/list": {
            "get": {
                "description": "获取指定回答的评论列表，使用游标分页，包含点赞/点踩统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "获取评论列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "回答ID",
                        "name": "answer_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"缺少回答ID\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/comment/replies": {
            "get": {
                "description": "获取指定评论的回复列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "获取评论回复",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "根评论ID",
                        "name": "root_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"缺少根评论ID\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/comment/{id}": {
            "get": {
                "description": "根据ID获取评论详细信息，包含点赞/点踩统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "获取评论详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"评论不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新评论内容（仅作者本人可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "更新评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"更新成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"评论不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除评论（仅作者本人可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "删除评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"删除成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"评论不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/follow": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "关注或取消关注问题/用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注管理"
                ],
                "summary": "关注/取消关注",
                "parameters": [
                    {
                        "description": "关注参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.FollowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"操作成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/follow/batch-status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "批量检查是否关注了指定目标列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注管理"
                ],
                "summary": "批量检查关注状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目标类型(1=问题,4=用户)",
                        "name": "target_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目标ID列表，逗号分隔",
                        "name": "target_ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"1\\\": true, \\\"2\\\": false}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/follow/followers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取关注当前用户的粉丝列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注管理"
                ],
                "summary": "获取粉丝列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "游标",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/follow/following": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取用户关注的用户/问题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注管理"
                ],
                "summary": "获取关注列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 4,
                        "description": "目标类型(1=问题,4=用户)",
                        "name": "target_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "游标",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/follow/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "检查是否关注了指定目标",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注管理"
                ],
                "summary": "检查关注状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目标类型(1=问题,4=用户)",
                        "name": "target_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "目标ID",
                        "name": "target_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"is_following\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "使用账号密码获取 Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "$ref": "#/definitions/controller.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Token 已过期或无效",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/question": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新问题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题管理"
                ],
                "summary": "创建问题",
                "parameters": [
                    {
                        "description": "问题参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"创建成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/question/list": {
            "get": {
                "description": "获取问题列表，使用游标分页，包含点赞/点踩/评论统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题管理"
                ],
                "summary": "获取问题列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "标签ID筛选",
                        "name": "tag_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/question/{id}": {
            "get": {
                "description": "根据ID获取问题详细信息，包含点赞/点踩/评论统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题管理"
                ],
                "summary": "获取问题详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "问题ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"问题不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新问题信息（仅作者本人可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题管理"
                ],
                "summary": "更新问题",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "问题ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"更新成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"问题不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除问题（仅作者本人可操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题管理"
                ],
                "summary": "删除问题",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "问题ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"删除成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "403": {
                        "description": "{\\\"code\\\": 403, \\\"message\\\": \\\"无权限操作\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"问题不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/reaction": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对问题、回答或评论进行点赞(1)、点踩(2)或取消(0)操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "互动管理"
                ],
                "summary": "执行点赞/点踩操作",
                "parameters": [
                    {
                        "description": "操作参数 (target_type: 1=问题 2=回答 3=评论, action: 0=取消 1=点赞 2=点踩)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"操作成功\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/reaction/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户对指定对象的状态 (0=无 1=点赞 2=点踩)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "互动管理"
                ],
                "summary": "获取点赞/点踩状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "对象类型 (1=问题 2=回答 3=评论)",
                        "name": "target_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "对象ID",
                        "name": "target_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"status\\\": 1}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用旧 Token 换取新 Token (需要在 Header 带上 Authorization)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "刷新 Token",
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "$ref": "#/definitions/controller.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Token 已过期或无效",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "创建新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户注册接口",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"注册成功，请去登录\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"id\\\": 1, \\\"username\\\": \\\"admin\\\", \\\"role\\\": \\\"admin\\\", \\\"avatar\\\": \\\"\\\"}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前用户的个人资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息"
                ],
                "summary": "更新用户资料",
                "parameters": [
                    {
                        "description": "更新参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"message\\\": \\\"更新成功\\\", \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "400": {
                        "description": "{\\\"code\\\": 400, \\\"message\\\": \\\"参数错误\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "401": {
                        "description": "{\\\"code\\\": 401, \\\"message\\\": \\\"未授权\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "获取指定用户的详细信息和统计数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息"
                ],
                "summary": "获取用户主页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {...}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"用户不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/user/{id}/answers": {
            "get": {
                "description": "获取指定用户发布的所有回答，使用游标分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息"
                ],
                "summary": "获取用户的回答列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"用户不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/user/{id}/questions": {
            "get": {
                "description": "获取指定用户发布的所有问题，使用游标分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息"
                ],
                "summary": "获取用户的问题列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标（上一页最后一条记录的ID）",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"code\\\": 200, \\\"data\\\": {\\\"list\\\": [...], \\\"next_cursor\\\": 123, \\\"has_more\\\": true}}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    },
                    "404": {
                        "description": "{\\\"code\\\": 404, \\\"message\\\": \\\"用户不存在\\\"}",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.AddToCollectionRequest": {
            "type": "object",
            "required": [
                "answer_id",
                "collection_id"
            ],
            "properties": {
                "answer_id": {
                    "type": "integer"
                },
                "collection_id": {
                    "type": "integer"
                }
            }
        },
        "controller.CreateAnswerRequest": {
            "type": "object",
            "required": [
                "content",
                "question_id"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 10
                },
                "question_id": {
                    "type": "integer"
                }
            }
        },
        "controller.CreateCollectionRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "controller.CreateCommentRequest": {
            "type": "object",
            "required": [
                "answer_id",
                "content"
            ],
            "properties": {
                "answer_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string",
                    "minLength": 1
                },
                "parent_id": {
                    "type": "integer"
                },
                "root_id": {
                    "type": "integer"
                }
            }
        },
        "controller.CreateQuestionRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 5
                }
            }
        },
        "controller.FollowRequest": {
            "type": "object",
            "required": [
                "target_id",
                "target_type"
            ],
            "properties": {
                "action": {
                    "description": "true=关注, false=取消关注",
                    "type": "boolean"
                },
                "target_id": {
                    "type": "integer"
                },
                "target_type": {
                    "description": "1=问题, 4=用户",
                    "type": "integer",
                    "enum": [
                        1,
                        4
                    ]
                }
            }
        },
        "controller.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "controller.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "expire": {
                    "type": "string",
                    "example": "2026-01-20T12:00:00Z"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "controller.ReactionRequest": {
            "type": "object",
            "required": [
                "target_id",
                "target_type"
            ],
            "properties": {
                "action": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "target_id": {
                    "type": "integer",
                    "minimum": 1
                },
                "target_type": {
                    "type": "integer",
                    "maximum": 4,
                    "minimum": 1
                }
            }
        },
        "controller.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "$ref": "#/definitions/model.UserRole"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "controller.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "controller.UpdateAnswerRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 10
                }
            }
        },
        "controller.UpdateCommentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "controller.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "controller.UpdateQuestionRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 5
                }
            }
        },
        "model.UserRole": {
            "type": "string",
            "enum": [
                "user",
                "admin",
                "agent"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleAdmin",
                "RoleAgent"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AgentTalk API",
	Description:      "这是一个类似知乎的问答平台 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
